import { jsPDF } from 'jspdf';

export function generatePDFReport(data: any) {
  try {
    const doc = new jsPDF();
    let y = 20;
    const lm = 20; // left margin
    const pw = 170; // page width

    const addTitle = (text: string) => {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(text, lm, y);
      y += 8;
      doc.setDrawColor(0, 180, 180);
      doc.line(lm, y, lm + pw, y);
      y += 6;
    };

    const addRow = (label: string, value: string) => {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(label, lm, y);
      doc.setFont('helvetica', 'bold');
      doc.text(String(value), lm + 90, y);
      y += 6;
    };

    const addText = (text: string) => {
      if (!text) return;
      if (y > 275) { doc.addPage(); y = 20; }
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(text, lm, y, { maxWidth: pw });
      y += 5;
    };

    const formatNum = (num: any) => {
      if (num === null || num === undefined) return '0';
      return typeof num === 'number' ? num.toLocaleString() : String(num);
    };

    // Cover
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('STRUCTURAL DESIGN REPORT', 105, 60, { align: 'center' });
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('As per IS 456:2000 & IS 10262:2019', 105, 72, { align: 'center' });
    doc.text(`Project: ${data.projectName || 'Untitled'}`, 105, 85, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 95, { align: 'center' });
    doc.text('Generated by BuildWise Planner', 105, 110, { align: 'center' });

    // Building Input
    doc.addPage();
    y = 20;
    // Building Input
    doc.addPage();
    y = 20;
    if (data.building) {
      addTitle('1. PROJECT SPECIFICATIONS');
      addRow('Length / Breadth:', `${data.buildingInput?.length ?? 0} ft / ${data.buildingInput?.breadth ?? 0} ft`);
      addRow('Overall Height:', `${data.buildingInput?.totalHeight ?? 0} ft`);
      addRow('Number of Floors:', data.building.floorLabel || 'G');
      addRow('Built-up Area / Floor:', `${formatNum(data.building.builtUpAreaPerFloor)} sq ft`);
      addRow('Total Built-up Area:', `${formatNum(data.building.totalBuiltUpArea)} sq ft`);
      
      y += 4;
      doc.setFontSize(10); doc.setFont('helvetica', 'bold');
      doc.text('WALL ESTIMATION (PERIMETER BASED)', lm, y); y += 6;
      addRow('Outer Wall Bricks (9"):', formatNum(data.building.outerBricks));
      addRow('Inner Wall Bricks (4.5"):', formatNum(data.building.innerBricks));
      addRow('Total Bricks (Final):', formatNum(data.building.brickQuantity));
      y += 4;
    }

    // Structural Specs (Background calculated)
    if (data.structural) {
      addTitle('2. PRELIMINARY STRUCTURAL SIZING');
      addRow('Slab Thickness:', `${data.structural.slabThickness} mm`);
      addRow('Beam Size (Typical):', `${data.structural.beamWidth} x ${data.structural.beamDepth} mm`);
      addRow('Column Size (Typical):', `${data.structural.columnWidth} x ${data.structural.columnDepth} mm`);
      addRow('Estimated Steel Density:', '3.5 - 4.5 kg/sq.ft');
      addRow('Reinforcement Standard:', 'Fe 500D (TMT)');
      y += 4;
    }

    // Column Grid
    if (data.columnGrid) {
      addTitle('3. COLUMN & GRID GEOMETRY');
      addRow('Total Column Nodes:', `${data.columnGrid.totalColumns ?? 0}`);
      addRow('Grid Spacing (Length):', `${(data.columnGrid.spacingLength ?? 0).toFixed(2)} ft`);
      addRow('Grid Spacing (Breadth):', `${(data.columnGrid.spacingBreadth ?? 0).toFixed(2)} ft`);
      addRow('Compliance:', 'IS 456 (Deflection Controlled)');
      y += 4;
    }

    // BHK Plan
    if (data.bhkPlan) {
      addTitle('4. ARCHITECTURAL ROOM MATRIX');
      addRow('BHK Configuration:', `${data.bhkPlan.bhk} BHK Unit`);
      addRow('Total Carpet Area:', `${formatNum(data.bhkPlan.carpetArea)} sq ft`);
      addRow('Wall/Circulation Area:', `${formatNum(data.bhkPlan.wallArea)} sq ft`);
      
      y += 5;
      doc.setFontSize(9); doc.setFont('helvetica', 'bold');
      doc.text('Detailed Room Dimensions:', lm, y); y += 6;
      (data.bhkPlan.rooms || []).forEach((r: any) => {
        addRow(`- ${r.name} (F${r.floor}):`, `${r.lengthFt}' × ${r.breadthFt}' [${r.area} sqft]`);
      });
      y += 4;
    }

    // Concrete Design
    if (data.concrete) {
      addTitle('5. CONCRETE MIX DESIGN (IS 10262:2019)');
      addRow('Concrete Grade:', data.concrete.grade);
      addRow('Durability Exposure:', data.concrete.exposure);
      addRow('Specified Slump:', `${data.concrete.slump} mm`);
      addRow('Target Mean Strength:', `${data.concrete.targetStrength} MPa`);
      addRow('Water-Cement Ratio:', `${data.concrete.waterCementRatio}`);
      
      const isNominal = parseInt(data.concrete.grade.substring(1)) < 25;
      if (isNominal) {
        addRow('Nominal Proportions:', '1 : 1.5 : 3 (M20)');
      }

      y += 6;
      doc.setFontSize(10); doc.setFont('helvetica', 'bold');
      doc.text('LABORATORY MIX PROPORTIONS (PER CUBIC METER)', lm, y);
      y += 6;
      const vol = data.concrete.volumeM3;
      addRow('Cement:', `${formatNum(Math.ceil(data.concrete.cementKg / vol))} kg [${(data.concrete.cementKg / vol / 50).toFixed(1)} Bags]`);
      addRow('Fine Aggregate (Sand):', `${formatNum(Math.ceil(data.concrete.sandKg / vol))} kg [${(data.concrete.sandKg / vol * 0.0353).toFixed(1)} CFT]`);
      addRow('Coarse Aggregate:', `${formatNum(Math.ceil(data.concrete.aggregateKg / vol))} kg [${(data.concrete.aggregateKg / vol * 0.0353).toFixed(1)} CFT]`);
      addRow('Chemical Admixture:', `${(data.concrete.admixtureKg / vol).toFixed(2)} kg`);
      addRow('Final Water Content:', `${formatNum(Math.ceil(data.concrete.waterLiters / vol))} Liters`);

      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.text('PHASE II: SITE BATCHING VALUES (FOR TOTAL VOLUME)', lm, y);
      y += 6;
      addRow('Total Concrete Volume:', `${data.concrete.volumeM3} m3`);
      addRow('Total Cement Required:', `${Math.ceil(data.concrete.cementKg / 50)} Bags`);
      addRow('Wet Sand (Corrected):', `${formatNum(data.concrete.correctedSand)} kg`);
      addRow('Wet Aggregate (Corrected):', `${formatNum(data.concrete.correctedAgg)} kg`);
      addRow('Adjusted Water Mixing:', `${formatNum(data.concrete.correctedWater)} Liters`);
      
      y += 10;
      doc.setTextColor(200, 0, 0);
      doc.setFontSize(8);
      doc.text('CIVIL WARNING: FIELD MOISTURE CORRECTION APPLIED. TRIAL MIX VALIDATION IS MANDATORY.', lm, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
    }

    // Plastering
    if (data.plastering) {
      addTitle('6. FINISHING & PLASTERING');
      addRow('Total Plaster Area:', `${formatNum(data.plastering.area)} sq ft`);
      addRow('Specified Thickness:', `${data.plastering.thicknessMm} mm`);
      addRow('Cement Bags (1:4):', formatNum(data.plastering.cementBags));
      addRow('Fine Sand Volume:', `${formatNum(data.plastering.sandM3)} m3`);
      y += 4;
    }

    // Trial Mix Table
    if (data.concrete?.trials) {
      doc.addPage();
      y = 20;
      addTitle('APPENDIX A: LABORATORY TRIAL SESSIONS');
      data.concrete.trials.forEach((t: any) => {
        doc.setFontSize(9); doc.setFont('helvetica', 'bold');
        doc.text(`TRIAL ${t.id} - ${t.label}`, lm, y); y += 5;
        doc.setFont('helvetica', 'normal');
        addText(`Water-Cement Ratio: ${t.wcr.toFixed(3)} | Admixture: ${t.admixture}% | Slump: Target`);
        addText(`Batch: Cement ${t.cementKg.toFixed(1)}kg, Water ${t.waterLiters.toFixed(1)}L, Sand ${t.sandKg.toFixed(1)}kg, Agg ${t.aggKg.toFixed(1)}kg`);
        y += 4;
      });
    }

    // Sanitize filename for Windows compatibility
    const safeProjectName = (data.projectName || 'BuildWise_Report')
      .replace(/[<>:"/\\|?*]/g, '_') // Remove chars windows doesn't like
      .trim();
    
    doc.save(`${safeProjectName}.pdf`);
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}
